name: action
on:
  pull_request:
    branches:
      - main

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: install
      run: npm install --legacy-peer-deps # ¯\_(ツ)_/¯

    - name: lint
      run: npm run lint

    # split up npm run test because cypress in docker is hard

    - name: vitest
      run: npm run vitest

    - name: cypress
      uses: cypress-io/github-action@v2
      with:
        start: npm run dev
        wait-on: http://localhost:1337